import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">WebHome</Link>
        </li>
        <li>
          <Link to="/webcitieshyderabad">WebCitiesHyderabad</Link>
        </li>
        <li>
          <Link to="/webfooddining">WebFoodDining</Link>
        </li>
        <li>
          <Link to="/webshopping">WebShopping</Link>
        </li>
        <li>
          <Link to="/webweekendgateways">WebWeekendGateways</Link>
        </li>
        <li>
          <Link to="/webeventsfestivals">WebEventsFestivals</Link>
        </li>
        <li>
          <Link to="/webexploremore">WebExploreMore</Link>
        </li>
        <li>
          <Link to="/webwebstories">WebWebStories</Link>
        </li>
        <li>
          <Link to="/webvideos">WebVideos</Link>
        </li>
        <li>
          <Link to="/webfoodarticle">WebFoodArticle</Link>
        </li>
        <li>
          <Link to="/webmoviearticle">WebMovieArticle</Link>
        </li>
        <li>
          <Link to="/webtecharticle">WebTechArticle</Link>
        </li>
        <li>
          <Link to="/webnormalarticle">WebNormalArticle</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
